-- Run this once in Supabase SQL Editor (new project: zvhwzitwxxhcnxwswzgq)
-- Sets up schema + permissions for Shubham Xerox backup restore

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Drop old tables (safe fresh restore)
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.photocopy_orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.free_notes CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.site_visits CASCADE;

CREATE TABLE public.users (
  phone TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  email TEXT
);

CREATE TABLE public.free_notes (
  id UUID PRIMARY KEY,
  title TEXT NOT NULL,
  file_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  is_paid BOOLEAN NOT NULL DEFAULT false,
  price NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE public.products (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  img TEXT,
  "desc" TEXT,
  exam TEXT,
  free_note_id UUID REFERENCES public.free_notes(id) ON DELETE SET NULL
);

CREATE TABLE public.orders (
  id TEXT PRIMARY KEY,
  customer TEXT NOT NULL,
  customerphone TEXT NOT NULL,
  address TEXT NOT NULL,
  total NUMERIC NOT NULL,
  method TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending',
  date TEXT NOT NULL,
  items JSONB NOT NULL
);

CREATE TABLE public.photocopy_orders (
  id TEXT PRIMARY KEY,
  customer_name TEXT,
  customer_phone TEXT,
  address TEXT,
  pages INTEGER,
  copies INTEGER,
  print_type TEXT,
  paper_size TEXT,
  sides TEXT,
  delivery_mode TEXT,
  total_cost NUMERIC,
  payment_method TEXT,
  doc_url TEXT,
  doc_path TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  transaction_id TEXT,
  tracking_url TEXT
);

CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender TEXT NOT NULL,
  receiver TEXT NOT NULL,
  message TEXT,
  file_url TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

CREATE TABLE public.site_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Disable RLS (app uses custom auth)
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.free_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.photocopy_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_visits DISABLE ROW LEVEL SECURITY;

-- Grants for anon/authenticated/service_role
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- Storage buckets (PDFs / images)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('free-notes', 'free-notes', true, 104857600, ARRAY['application/pdf']),
  ('photocopy-docs', 'photocopy-docs', true, 104857600, ARRAY['application/pdf']),
  ('products', 'products', true, 104857600, ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp']),
  ('chat-files', 'chat-files', true, 104857600, NULL)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Public read app storage files" ON storage.objects;
CREATE POLICY "Public read app storage files"
ON storage.objects FOR SELECT
USING (bucket_id IN ('free-notes', 'photocopy-docs', 'products', 'chat-files'));

DROP POLICY IF EXISTS "Public upload app storage files" ON storage.objects;
CREATE POLICY "Public upload app storage files"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id IN ('free-notes', 'photocopy-docs', 'products', 'chat-files'));

DROP POLICY IF EXISTS "Public update app storage files" ON storage.objects;
CREATE POLICY "Public update app storage files"
ON storage.objects FOR UPDATE
USING (bucket_id IN ('free-notes', 'photocopy-docs', 'products', 'chat-files'))
WITH CHECK (bucket_id IN ('free-notes', 'photocopy-docs', 'products', 'chat-files'));

DROP POLICY IF EXISTS "Public delete app storage files" ON storage.objects;
CREATE POLICY "Public delete app storage files"
ON storage.objects FOR DELETE
USING (bucket_id IN ('free-notes', 'photocopy-docs', 'products', 'chat-files'));
