-- Supabase Setup Script for Shubham Xerox

-- 1. Create Users Table
CREATE TABLE public.users (
  phone TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'user'
);

-- 2. Create Products Table
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  img TEXT,
  "desc" TEXT
);

-- 3. Create Orders Table
CREATE TABLE public.orders (
  id TEXT PRIMARY KEY,
  customer TEXT NOT NULL,
  customerPhone TEXT NOT NULL,
  address TEXT NOT NULL,
  total NUMERIC NOT NULL,
  method TEXT NOT NULL,
  status TEXT DEFAULT 'Pending',
  date TEXT NOT NULL,
  items JSONB NOT NULL
);

-- 4. Create Reviews Table
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Disable Row Level Security (RLS) for public access during Database integration without Auth constraints
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;

-- 5. Create Site Visits Table
CREATE TABLE public.site_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.site_visits DISABLE ROW LEVEL SECURITY;
